# Generated by Django 5.2.14 on 2026-05-21 05:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0001_initial"),
        ("votes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["election", "position"], name="votes_electio_09276f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["candidate"], name="votes_candida_da1a33_idx"),
        ),
    ]
