# Generated by Django 5.2.14 on 2026-08-31 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0003_candidateapplication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="candidateapplication",
            name="unique_candidate_application",
        ),
        migrations.AddConstraint(
            model_name="candidateapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PENDING", "APPROVED"])),
                fields=("applicant", "election", "position"),
                name="unique_active_candidate_application",
            ),
        ),
    ]
